
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'BaseFooter': typeof import("../../app/components/Base/BaseFooter.vue").default
  'BaseHeader': typeof import("../../app/components/Base/BaseHeader.vue").default
  'BaseHeaderNav': typeof import("../../app/components/Base/BaseHeaderNav.vue").default
  'Income': typeof import("../../app/components/Income.vue").default
  'ModelIncome': typeof import("../../app/components/Model/Income.vue").default
  'PathBreadcrumbs': typeof import("../../app/components/Path/PathBreadcrumbs.vue").default
  'PathIndex': typeof import("../../app/components/Path/PathIndex.vue").default
  'PathItemFiles': typeof import("../../app/components/Path/PathItemFiles.vue").default
  'PathReadme': typeof import("../../app/components/Path/PathReadme.vue").default
  'SearchCommand': typeof import("../../app/components/SearchCommand.vue").default
  'ThemeToggle': typeof import("../../app/components/ThemeToggle.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'Avatar': typeof import("../../app/components/ui/avatar/index").Avatar
  'AvatarFallback': typeof import("../../app/components/ui/avatar/index").AvatarFallback
  'AvatarImage': typeof import("../../app/components/ui/avatar/index").AvatarImage
  'Badge': typeof import("../../app/components/ui/badge/index").Badge
  'Breadcrumb': typeof import("../../app/components/ui/breadcrumb/index").Breadcrumb
  'BreadcrumbEllipsis': typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbEllipsis
  'BreadcrumbItem': typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbItem
  'BreadcrumbLink': typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbLink
  'BreadcrumbList': typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbList
  'BreadcrumbPage': typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbPage
  'BreadcrumbSeparator': typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbSeparator
  'Button': typeof import("../../app/components/ui/button/index").Button
  'Command': typeof import("../../app/components/ui/command/index").Command
  'CommandDialog': typeof import("../../app/components/ui/command/index").CommandDialog
  'CommandEmpty': typeof import("../../app/components/ui/command/index").CommandEmpty
  'CommandGroup': typeof import("../../app/components/ui/command/index").CommandGroup
  'CommandInput': typeof import("../../app/components/ui/command/index").CommandInput
  'CommandItem': typeof import("../../app/components/ui/command/index").CommandItem
  'CommandList': typeof import("../../app/components/ui/command/index").CommandList
  'CommandSeparator': typeof import("../../app/components/ui/command/index").CommandSeparator
  'CommandShortcut': typeof import("../../app/components/ui/command/index").CommandShortcut
  'Card': typeof import("../../app/components/ui/card/index").Card
  'CardAction': typeof import("../../app/components/ui/card/index").CardAction
  'CardContent': typeof import("../../app/components/ui/card/index").CardContent
  'CardDescription': typeof import("../../app/components/ui/card/index").CardDescription
  'CardFooter': typeof import("../../app/components/ui/card/index").CardFooter
  'CardHeader': typeof import("../../app/components/ui/card/index").CardHeader
  'CardTitle': typeof import("../../app/components/ui/card/index").CardTitle
  'Dialog': typeof import("../../app/components/ui/dialog/index").Dialog
  'DialogClose': typeof import("../../app/components/ui/dialog/index").DialogClose
  'DialogContent': typeof import("../../app/components/ui/dialog/index").DialogContent
  'DialogDescription': typeof import("../../app/components/ui/dialog/index").DialogDescription
  'DialogFooter': typeof import("../../app/components/ui/dialog/index").DialogFooter
  'DialogHeader': typeof import("../../app/components/ui/dialog/index").DialogHeader
  'DialogOverlay': typeof import("../../app/components/ui/dialog/index").DialogOverlay
  'DialogScrollContent': typeof import("../../app/components/ui/dialog/index").DialogScrollContent
  'DialogTitle': typeof import("../../app/components/ui/dialog/index").DialogTitle
  'DialogTrigger': typeof import("../../app/components/ui/dialog/index").DialogTrigger
  'DropdownMenu': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenu
  'DropdownMenuCheckboxItem': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuCheckboxItem
  'DropdownMenuContent': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuContent
  'DropdownMenuGroup': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuGroup
  'DropdownMenuItem': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuItem
  'DropdownMenuLabel': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuLabel
  'DropdownMenuRadioGroup': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuRadioGroup
  'DropdownMenuRadioItem': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuRadioItem
  'DropdownMenuSeparator': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSeparator
  'DropdownMenuShortcut': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuShortcut
  'DropdownMenuSub': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSub
  'DropdownMenuSubContent': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSubContent
  'DropdownMenuSubTrigger': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSubTrigger
  'DropdownMenuTrigger': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuTrigger
  'DropdownMenuPortal': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuPortal
  'Empty': typeof import("../../app/components/ui/empty/index").Empty
  'EmptyContent': typeof import("../../app/components/ui/empty/index").EmptyContent
  'EmptyDescription': typeof import("../../app/components/ui/empty/index").EmptyDescription
  'EmptyHeader': typeof import("../../app/components/ui/empty/index").EmptyHeader
  'EmptyMedia': typeof import("../../app/components/ui/empty/index").EmptyMedia
  'EmptyTitle': typeof import("../../app/components/ui/empty/index").EmptyTitle
  'Input': typeof import("../../app/components/ui/input/index").Input
  'NavigationMenu': typeof import("../../app/components/ui/navigation-menu/index").NavigationMenu
  'NavigationMenuContent': typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuContent
  'NavigationMenuIndicator': typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuIndicator
  'NavigationMenuItem': typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuItem
  'NavigationMenuLink': typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuLink
  'NavigationMenuList': typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuList
  'NavigationMenuTrigger': typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuTrigger
  'NavigationMenuViewport': typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuViewport
  'Pagination': typeof import("../../app/components/ui/pagination/index").Pagination
  'PaginationContent': typeof import("../../app/components/ui/pagination/index").PaginationContent
  'PaginationEllipsis': typeof import("../../app/components/ui/pagination/index").PaginationEllipsis
  'PaginationFirst': typeof import("../../app/components/ui/pagination/index").PaginationFirst
  'PaginationItem': typeof import("../../app/components/ui/pagination/index").PaginationItem
  'PaginationLast': typeof import("../../app/components/ui/pagination/index").PaginationLast
  'PaginationNext': typeof import("../../app/components/ui/pagination/index").PaginationNext
  'PaginationPrevious': typeof import("../../app/components/ui/pagination/index").PaginationPrevious
  'Progress': typeof import("../../app/components/ui/progress/index").Progress
  'Select': typeof import("../../app/components/ui/select/index").Select
  'SelectContent': typeof import("../../app/components/ui/select/index").SelectContent
  'SelectGroup': typeof import("../../app/components/ui/select/index").SelectGroup
  'SelectItem': typeof import("../../app/components/ui/select/index").SelectItem
  'SelectItemText': typeof import("../../app/components/ui/select/index").SelectItemText
  'SelectLabel': typeof import("../../app/components/ui/select/index").SelectLabel
  'SelectScrollDownButton': typeof import("../../app/components/ui/select/index").SelectScrollDownButton
  'SelectScrollUpButton': typeof import("../../app/components/ui/select/index").SelectScrollUpButton
  'SelectSeparator': typeof import("../../app/components/ui/select/index").SelectSeparator
  'SelectTrigger': typeof import("../../app/components/ui/select/index").SelectTrigger
  'SelectValue': typeof import("../../app/components/ui/select/index").SelectValue
  'ScrollArea': typeof import("../../app/components/ui/scroll-area/index").ScrollArea
  'ScrollBar': typeof import("../../app/components/ui/scroll-area/index").ScrollBar
  'Separator': typeof import("../../app/components/ui/separator/index").Separator
  'Skeleton': typeof import("../../app/components/ui/skeleton/index").Skeleton
  'Switch': typeof import("../../app/components/ui/switch/index").Switch
  'Sheet': typeof import("../../app/components/ui/sheet/index").Sheet
  'SheetClose': typeof import("../../app/components/ui/sheet/index").SheetClose
  'SheetContent': typeof import("../../app/components/ui/sheet/index").SheetContent
  'SheetDescription': typeof import("../../app/components/ui/sheet/index").SheetDescription
  'SheetFooter': typeof import("../../app/components/ui/sheet/index").SheetFooter
  'SheetHeader': typeof import("../../app/components/ui/sheet/index").SheetHeader
  'SheetTitle': typeof import("../../app/components/ui/sheet/index").SheetTitle
  'SheetTrigger': typeof import("../../app/components/ui/sheet/index").SheetTrigger
  'Tooltip': typeof import("../../app/components/ui/tooltip/index").Tooltip
  'TooltipContent': typeof import("../../app/components/ui/tooltip/index").TooltipContent
  'TooltipProvider': typeof import("../../app/components/ui/tooltip/index").TooltipProvider
  'TooltipTrigger': typeof import("../../app/components/ui/tooltip/index").TooltipTrigger
  'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyBaseFooter': LazyComponent<typeof import("../../app/components/Base/BaseFooter.vue").default>
  'LazyBaseHeader': LazyComponent<typeof import("../../app/components/Base/BaseHeader.vue").default>
  'LazyBaseHeaderNav': LazyComponent<typeof import("../../app/components/Base/BaseHeaderNav.vue").default>
  'LazyIncome': LazyComponent<typeof import("../../app/components/Income.vue").default>
  'LazyModelIncome': LazyComponent<typeof import("../../app/components/Model/Income.vue").default>
  'LazyPathBreadcrumbs': LazyComponent<typeof import("../../app/components/Path/PathBreadcrumbs.vue").default>
  'LazyPathIndex': LazyComponent<typeof import("../../app/components/Path/PathIndex.vue").default>
  'LazyPathItemFiles': LazyComponent<typeof import("../../app/components/Path/PathItemFiles.vue").default>
  'LazyPathReadme': LazyComponent<typeof import("../../app/components/Path/PathReadme.vue").default>
  'LazySearchCommand': LazyComponent<typeof import("../../app/components/SearchCommand.vue").default>
  'LazyThemeToggle': LazyComponent<typeof import("../../app/components/ThemeToggle.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyAvatar': LazyComponent<typeof import("../../app/components/ui/avatar/index").Avatar>
  'LazyAvatarFallback': LazyComponent<typeof import("../../app/components/ui/avatar/index").AvatarFallback>
  'LazyAvatarImage': LazyComponent<typeof import("../../app/components/ui/avatar/index").AvatarImage>
  'LazyBadge': LazyComponent<typeof import("../../app/components/ui/badge/index").Badge>
  'LazyBreadcrumb': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index").Breadcrumb>
  'LazyBreadcrumbEllipsis': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbEllipsis>
  'LazyBreadcrumbItem': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbItem>
  'LazyBreadcrumbLink': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbLink>
  'LazyBreadcrumbList': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbList>
  'LazyBreadcrumbPage': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbPage>
  'LazyBreadcrumbSeparator': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index").BreadcrumbSeparator>
  'LazyButton': LazyComponent<typeof import("../../app/components/ui/button/index").Button>
  'LazyCommand': LazyComponent<typeof import("../../app/components/ui/command/index").Command>
  'LazyCommandDialog': LazyComponent<typeof import("../../app/components/ui/command/index").CommandDialog>
  'LazyCommandEmpty': LazyComponent<typeof import("../../app/components/ui/command/index").CommandEmpty>
  'LazyCommandGroup': LazyComponent<typeof import("../../app/components/ui/command/index").CommandGroup>
  'LazyCommandInput': LazyComponent<typeof import("../../app/components/ui/command/index").CommandInput>
  'LazyCommandItem': LazyComponent<typeof import("../../app/components/ui/command/index").CommandItem>
  'LazyCommandList': LazyComponent<typeof import("../../app/components/ui/command/index").CommandList>
  'LazyCommandSeparator': LazyComponent<typeof import("../../app/components/ui/command/index").CommandSeparator>
  'LazyCommandShortcut': LazyComponent<typeof import("../../app/components/ui/command/index").CommandShortcut>
  'LazyCard': LazyComponent<typeof import("../../app/components/ui/card/index").Card>
  'LazyCardAction': LazyComponent<typeof import("../../app/components/ui/card/index").CardAction>
  'LazyCardContent': LazyComponent<typeof import("../../app/components/ui/card/index").CardContent>
  'LazyCardDescription': LazyComponent<typeof import("../../app/components/ui/card/index").CardDescription>
  'LazyCardFooter': LazyComponent<typeof import("../../app/components/ui/card/index").CardFooter>
  'LazyCardHeader': LazyComponent<typeof import("../../app/components/ui/card/index").CardHeader>
  'LazyCardTitle': LazyComponent<typeof import("../../app/components/ui/card/index").CardTitle>
  'LazyDialog': LazyComponent<typeof import("../../app/components/ui/dialog/index").Dialog>
  'LazyDialogClose': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogClose>
  'LazyDialogContent': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogContent>
  'LazyDialogDescription': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogDescription>
  'LazyDialogFooter': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogFooter>
  'LazyDialogHeader': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogHeader>
  'LazyDialogOverlay': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogOverlay>
  'LazyDialogScrollContent': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogScrollContent>
  'LazyDialogTitle': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogTitle>
  'LazyDialogTrigger': LazyComponent<typeof import("../../app/components/ui/dialog/index").DialogTrigger>
  'LazyDropdownMenu': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenu>
  'LazyDropdownMenuCheckboxItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuCheckboxItem>
  'LazyDropdownMenuContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuContent>
  'LazyDropdownMenuGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuGroup>
  'LazyDropdownMenuItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuItem>
  'LazyDropdownMenuLabel': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuLabel>
  'LazyDropdownMenuRadioGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuRadioGroup>
  'LazyDropdownMenuRadioItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuRadioItem>
  'LazyDropdownMenuSeparator': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSeparator>
  'LazyDropdownMenuShortcut': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuShortcut>
  'LazyDropdownMenuSub': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSub>
  'LazyDropdownMenuSubContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSubContent>
  'LazyDropdownMenuSubTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSubTrigger>
  'LazyDropdownMenuTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuTrigger>
  'LazyDropdownMenuPortal': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuPortal>
  'LazyEmpty': LazyComponent<typeof import("../../app/components/ui/empty/index").Empty>
  'LazyEmptyContent': LazyComponent<typeof import("../../app/components/ui/empty/index").EmptyContent>
  'LazyEmptyDescription': LazyComponent<typeof import("../../app/components/ui/empty/index").EmptyDescription>
  'LazyEmptyHeader': LazyComponent<typeof import("../../app/components/ui/empty/index").EmptyHeader>
  'LazyEmptyMedia': LazyComponent<typeof import("../../app/components/ui/empty/index").EmptyMedia>
  'LazyEmptyTitle': LazyComponent<typeof import("../../app/components/ui/empty/index").EmptyTitle>
  'LazyInput': LazyComponent<typeof import("../../app/components/ui/input/index").Input>
  'LazyNavigationMenu': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index").NavigationMenu>
  'LazyNavigationMenuContent': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuContent>
  'LazyNavigationMenuIndicator': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuIndicator>
  'LazyNavigationMenuItem': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuItem>
  'LazyNavigationMenuLink': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuLink>
  'LazyNavigationMenuList': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuList>
  'LazyNavigationMenuTrigger': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuTrigger>
  'LazyNavigationMenuViewport': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index").NavigationMenuViewport>
  'LazyPagination': LazyComponent<typeof import("../../app/components/ui/pagination/index").Pagination>
  'LazyPaginationContent': LazyComponent<typeof import("../../app/components/ui/pagination/index").PaginationContent>
  'LazyPaginationEllipsis': LazyComponent<typeof import("../../app/components/ui/pagination/index").PaginationEllipsis>
  'LazyPaginationFirst': LazyComponent<typeof import("../../app/components/ui/pagination/index").PaginationFirst>
  'LazyPaginationItem': LazyComponent<typeof import("../../app/components/ui/pagination/index").PaginationItem>
  'LazyPaginationLast': LazyComponent<typeof import("../../app/components/ui/pagination/index").PaginationLast>
  'LazyPaginationNext': LazyComponent<typeof import("../../app/components/ui/pagination/index").PaginationNext>
  'LazyPaginationPrevious': LazyComponent<typeof import("../../app/components/ui/pagination/index").PaginationPrevious>
  'LazyProgress': LazyComponent<typeof import("../../app/components/ui/progress/index").Progress>
  'LazySelect': LazyComponent<typeof import("../../app/components/ui/select/index").Select>
  'LazySelectContent': LazyComponent<typeof import("../../app/components/ui/select/index").SelectContent>
  'LazySelectGroup': LazyComponent<typeof import("../../app/components/ui/select/index").SelectGroup>
  'LazySelectItem': LazyComponent<typeof import("../../app/components/ui/select/index").SelectItem>
  'LazySelectItemText': LazyComponent<typeof import("../../app/components/ui/select/index").SelectItemText>
  'LazySelectLabel': LazyComponent<typeof import("../../app/components/ui/select/index").SelectLabel>
  'LazySelectScrollDownButton': LazyComponent<typeof import("../../app/components/ui/select/index").SelectScrollDownButton>
  'LazySelectScrollUpButton': LazyComponent<typeof import("../../app/components/ui/select/index").SelectScrollUpButton>
  'LazySelectSeparator': LazyComponent<typeof import("../../app/components/ui/select/index").SelectSeparator>
  'LazySelectTrigger': LazyComponent<typeof import("../../app/components/ui/select/index").SelectTrigger>
  'LazySelectValue': LazyComponent<typeof import("../../app/components/ui/select/index").SelectValue>
  'LazyScrollArea': LazyComponent<typeof import("../../app/components/ui/scroll-area/index").ScrollArea>
  'LazyScrollBar': LazyComponent<typeof import("../../app/components/ui/scroll-area/index").ScrollBar>
  'LazySeparator': LazyComponent<typeof import("../../app/components/ui/separator/index").Separator>
  'LazySkeleton': LazyComponent<typeof import("../../app/components/ui/skeleton/index").Skeleton>
  'LazySwitch': LazyComponent<typeof import("../../app/components/ui/switch/index").Switch>
  'LazySheet': LazyComponent<typeof import("../../app/components/ui/sheet/index").Sheet>
  'LazySheetClose': LazyComponent<typeof import("../../app/components/ui/sheet/index").SheetClose>
  'LazySheetContent': LazyComponent<typeof import("../../app/components/ui/sheet/index").SheetContent>
  'LazySheetDescription': LazyComponent<typeof import("../../app/components/ui/sheet/index").SheetDescription>
  'LazySheetFooter': LazyComponent<typeof import("../../app/components/ui/sheet/index").SheetFooter>
  'LazySheetHeader': LazyComponent<typeof import("../../app/components/ui/sheet/index").SheetHeader>
  'LazySheetTitle': LazyComponent<typeof import("../../app/components/ui/sheet/index").SheetTitle>
  'LazySheetTrigger': LazyComponent<typeof import("../../app/components/ui/sheet/index").SheetTrigger>
  'LazyTooltip': LazyComponent<typeof import("../../app/components/ui/tooltip/index").Tooltip>
  'LazyTooltipContent': LazyComponent<typeof import("../../app/components/ui/tooltip/index").TooltipContent>
  'LazyTooltipProvider': LazyComponent<typeof import("../../app/components/ui/tooltip/index").TooltipProvider>
  'LazyTooltipTrigger': LazyComponent<typeof import("../../app/components/ui/tooltip/index").TooltipTrigger>
  'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
