
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const BaseFooter: typeof import("../app/components/Base/BaseFooter.vue").default
export const BaseHeader: typeof import("../app/components/Base/BaseHeader.vue").default
export const BaseHeaderNav: typeof import("../app/components/Base/BaseHeaderNav.vue").default
export const Income: typeof import("../app/components/Income.vue").default
export const ModelIncome: typeof import("../app/components/Model/Income.vue").default
export const PathBreadcrumbs: typeof import("../app/components/Path/PathBreadcrumbs.vue").default
export const PathIndex: typeof import("../app/components/Path/PathIndex.vue").default
export const PathItemFiles: typeof import("../app/components/Path/PathItemFiles.vue").default
export const PathReadme: typeof import("../app/components/Path/PathReadme.vue").default
export const SearchCommand: typeof import("../app/components/SearchCommand.vue").default
export const ThemeToggle: typeof import("../app/components/ThemeToggle.vue").default
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const Avatar: typeof import("../app/components/ui/avatar/index").Avatar
export const AvatarFallback: typeof import("../app/components/ui/avatar/index").AvatarFallback
export const AvatarImage: typeof import("../app/components/ui/avatar/index").AvatarImage
export const Badge: typeof import("../app/components/ui/badge/index").Badge
export const Breadcrumb: typeof import("../app/components/ui/breadcrumb/index").Breadcrumb
export const BreadcrumbEllipsis: typeof import("../app/components/ui/breadcrumb/index").BreadcrumbEllipsis
export const BreadcrumbItem: typeof import("../app/components/ui/breadcrumb/index").BreadcrumbItem
export const BreadcrumbLink: typeof import("../app/components/ui/breadcrumb/index").BreadcrumbLink
export const BreadcrumbList: typeof import("../app/components/ui/breadcrumb/index").BreadcrumbList
export const BreadcrumbPage: typeof import("../app/components/ui/breadcrumb/index").BreadcrumbPage
export const BreadcrumbSeparator: typeof import("../app/components/ui/breadcrumb/index").BreadcrumbSeparator
export const Button: typeof import("../app/components/ui/button/index").Button
export const Command: typeof import("../app/components/ui/command/index").Command
export const CommandDialog: typeof import("../app/components/ui/command/index").CommandDialog
export const CommandEmpty: typeof import("../app/components/ui/command/index").CommandEmpty
export const CommandGroup: typeof import("../app/components/ui/command/index").CommandGroup
export const CommandInput: typeof import("../app/components/ui/command/index").CommandInput
export const CommandItem: typeof import("../app/components/ui/command/index").CommandItem
export const CommandList: typeof import("../app/components/ui/command/index").CommandList
export const CommandSeparator: typeof import("../app/components/ui/command/index").CommandSeparator
export const CommandShortcut: typeof import("../app/components/ui/command/index").CommandShortcut
export const Card: typeof import("../app/components/ui/card/index").Card
export const CardAction: typeof import("../app/components/ui/card/index").CardAction
export const CardContent: typeof import("../app/components/ui/card/index").CardContent
export const CardDescription: typeof import("../app/components/ui/card/index").CardDescription
export const CardFooter: typeof import("../app/components/ui/card/index").CardFooter
export const CardHeader: typeof import("../app/components/ui/card/index").CardHeader
export const CardTitle: typeof import("../app/components/ui/card/index").CardTitle
export const Dialog: typeof import("../app/components/ui/dialog/index").Dialog
export const DialogClose: typeof import("../app/components/ui/dialog/index").DialogClose
export const DialogContent: typeof import("../app/components/ui/dialog/index").DialogContent
export const DialogDescription: typeof import("../app/components/ui/dialog/index").DialogDescription
export const DialogFooter: typeof import("../app/components/ui/dialog/index").DialogFooter
export const DialogHeader: typeof import("../app/components/ui/dialog/index").DialogHeader
export const DialogOverlay: typeof import("../app/components/ui/dialog/index").DialogOverlay
export const DialogScrollContent: typeof import("../app/components/ui/dialog/index").DialogScrollContent
export const DialogTitle: typeof import("../app/components/ui/dialog/index").DialogTitle
export const DialogTrigger: typeof import("../app/components/ui/dialog/index").DialogTrigger
export const DropdownMenu: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenu
export const DropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuCheckboxItem
export const DropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuContent
export const DropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuGroup
export const DropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuItem
export const DropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuLabel
export const DropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuRadioGroup
export const DropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuRadioItem
export const DropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSeparator
export const DropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuShortcut
export const DropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSub
export const DropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSubContent
export const DropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSubTrigger
export const DropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuTrigger
export const DropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuPortal
export const Empty: typeof import("../app/components/ui/empty/index").Empty
export const EmptyContent: typeof import("../app/components/ui/empty/index").EmptyContent
export const EmptyDescription: typeof import("../app/components/ui/empty/index").EmptyDescription
export const EmptyHeader: typeof import("../app/components/ui/empty/index").EmptyHeader
export const EmptyMedia: typeof import("../app/components/ui/empty/index").EmptyMedia
export const EmptyTitle: typeof import("../app/components/ui/empty/index").EmptyTitle
export const Input: typeof import("../app/components/ui/input/index").Input
export const NavigationMenu: typeof import("../app/components/ui/navigation-menu/index").NavigationMenu
export const NavigationMenuContent: typeof import("../app/components/ui/navigation-menu/index").NavigationMenuContent
export const NavigationMenuIndicator: typeof import("../app/components/ui/navigation-menu/index").NavigationMenuIndicator
export const NavigationMenuItem: typeof import("../app/components/ui/navigation-menu/index").NavigationMenuItem
export const NavigationMenuLink: typeof import("../app/components/ui/navigation-menu/index").NavigationMenuLink
export const NavigationMenuList: typeof import("../app/components/ui/navigation-menu/index").NavigationMenuList
export const NavigationMenuTrigger: typeof import("../app/components/ui/navigation-menu/index").NavigationMenuTrigger
export const NavigationMenuViewport: typeof import("../app/components/ui/navigation-menu/index").NavigationMenuViewport
export const Pagination: typeof import("../app/components/ui/pagination/index").Pagination
export const PaginationContent: typeof import("../app/components/ui/pagination/index").PaginationContent
export const PaginationEllipsis: typeof import("../app/components/ui/pagination/index").PaginationEllipsis
export const PaginationFirst: typeof import("../app/components/ui/pagination/index").PaginationFirst
export const PaginationItem: typeof import("../app/components/ui/pagination/index").PaginationItem
export const PaginationLast: typeof import("../app/components/ui/pagination/index").PaginationLast
export const PaginationNext: typeof import("../app/components/ui/pagination/index").PaginationNext
export const PaginationPrevious: typeof import("../app/components/ui/pagination/index").PaginationPrevious
export const Progress: typeof import("../app/components/ui/progress/index").Progress
export const Select: typeof import("../app/components/ui/select/index").Select
export const SelectContent: typeof import("../app/components/ui/select/index").SelectContent
export const SelectGroup: typeof import("../app/components/ui/select/index").SelectGroup
export const SelectItem: typeof import("../app/components/ui/select/index").SelectItem
export const SelectItemText: typeof import("../app/components/ui/select/index").SelectItemText
export const SelectLabel: typeof import("../app/components/ui/select/index").SelectLabel
export const SelectScrollDownButton: typeof import("../app/components/ui/select/index").SelectScrollDownButton
export const SelectScrollUpButton: typeof import("../app/components/ui/select/index").SelectScrollUpButton
export const SelectSeparator: typeof import("../app/components/ui/select/index").SelectSeparator
export const SelectTrigger: typeof import("../app/components/ui/select/index").SelectTrigger
export const SelectValue: typeof import("../app/components/ui/select/index").SelectValue
export const ScrollArea: typeof import("../app/components/ui/scroll-area/index").ScrollArea
export const ScrollBar: typeof import("../app/components/ui/scroll-area/index").ScrollBar
export const Separator: typeof import("../app/components/ui/separator/index").Separator
export const Skeleton: typeof import("../app/components/ui/skeleton/index").Skeleton
export const Switch: typeof import("../app/components/ui/switch/index").Switch
export const Sheet: typeof import("../app/components/ui/sheet/index").Sheet
export const SheetClose: typeof import("../app/components/ui/sheet/index").SheetClose
export const SheetContent: typeof import("../app/components/ui/sheet/index").SheetContent
export const SheetDescription: typeof import("../app/components/ui/sheet/index").SheetDescription
export const SheetFooter: typeof import("../app/components/ui/sheet/index").SheetFooter
export const SheetHeader: typeof import("../app/components/ui/sheet/index").SheetHeader
export const SheetTitle: typeof import("../app/components/ui/sheet/index").SheetTitle
export const SheetTrigger: typeof import("../app/components/ui/sheet/index").SheetTrigger
export const Tooltip: typeof import("../app/components/ui/tooltip/index").Tooltip
export const TooltipContent: typeof import("../app/components/ui/tooltip/index").TooltipContent
export const TooltipProvider: typeof import("../app/components/ui/tooltip/index").TooltipProvider
export const TooltipTrigger: typeof import("../app/components/ui/tooltip/index").TooltipTrigger
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue").default
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyBaseFooter: LazyComponent<typeof import("../app/components/Base/BaseFooter.vue").default>
export const LazyBaseHeader: LazyComponent<typeof import("../app/components/Base/BaseHeader.vue").default>
export const LazyBaseHeaderNav: LazyComponent<typeof import("../app/components/Base/BaseHeaderNav.vue").default>
export const LazyIncome: LazyComponent<typeof import("../app/components/Income.vue").default>
export const LazyModelIncome: LazyComponent<typeof import("../app/components/Model/Income.vue").default>
export const LazyPathBreadcrumbs: LazyComponent<typeof import("../app/components/Path/PathBreadcrumbs.vue").default>
export const LazyPathIndex: LazyComponent<typeof import("../app/components/Path/PathIndex.vue").default>
export const LazyPathItemFiles: LazyComponent<typeof import("../app/components/Path/PathItemFiles.vue").default>
export const LazyPathReadme: LazyComponent<typeof import("../app/components/Path/PathReadme.vue").default>
export const LazySearchCommand: LazyComponent<typeof import("../app/components/SearchCommand.vue").default>
export const LazyThemeToggle: LazyComponent<typeof import("../app/components/ThemeToggle.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyAvatar: LazyComponent<typeof import("../app/components/ui/avatar/index").Avatar>
export const LazyAvatarFallback: LazyComponent<typeof import("../app/components/ui/avatar/index").AvatarFallback>
export const LazyAvatarImage: LazyComponent<typeof import("../app/components/ui/avatar/index").AvatarImage>
export const LazyBadge: LazyComponent<typeof import("../app/components/ui/badge/index").Badge>
export const LazyBreadcrumb: LazyComponent<typeof import("../app/components/ui/breadcrumb/index").Breadcrumb>
export const LazyBreadcrumbEllipsis: LazyComponent<typeof import("../app/components/ui/breadcrumb/index").BreadcrumbEllipsis>
export const LazyBreadcrumbItem: LazyComponent<typeof import("../app/components/ui/breadcrumb/index").BreadcrumbItem>
export const LazyBreadcrumbLink: LazyComponent<typeof import("../app/components/ui/breadcrumb/index").BreadcrumbLink>
export const LazyBreadcrumbList: LazyComponent<typeof import("../app/components/ui/breadcrumb/index").BreadcrumbList>
export const LazyBreadcrumbPage: LazyComponent<typeof import("../app/components/ui/breadcrumb/index").BreadcrumbPage>
export const LazyBreadcrumbSeparator: LazyComponent<typeof import("../app/components/ui/breadcrumb/index").BreadcrumbSeparator>
export const LazyButton: LazyComponent<typeof import("../app/components/ui/button/index").Button>
export const LazyCommand: LazyComponent<typeof import("../app/components/ui/command/index").Command>
export const LazyCommandDialog: LazyComponent<typeof import("../app/components/ui/command/index").CommandDialog>
export const LazyCommandEmpty: LazyComponent<typeof import("../app/components/ui/command/index").CommandEmpty>
export const LazyCommandGroup: LazyComponent<typeof import("../app/components/ui/command/index").CommandGroup>
export const LazyCommandInput: LazyComponent<typeof import("../app/components/ui/command/index").CommandInput>
export const LazyCommandItem: LazyComponent<typeof import("../app/components/ui/command/index").CommandItem>
export const LazyCommandList: LazyComponent<typeof import("../app/components/ui/command/index").CommandList>
export const LazyCommandSeparator: LazyComponent<typeof import("../app/components/ui/command/index").CommandSeparator>
export const LazyCommandShortcut: LazyComponent<typeof import("../app/components/ui/command/index").CommandShortcut>
export const LazyCard: LazyComponent<typeof import("../app/components/ui/card/index").Card>
export const LazyCardAction: LazyComponent<typeof import("../app/components/ui/card/index").CardAction>
export const LazyCardContent: LazyComponent<typeof import("../app/components/ui/card/index").CardContent>
export const LazyCardDescription: LazyComponent<typeof import("../app/components/ui/card/index").CardDescription>
export const LazyCardFooter: LazyComponent<typeof import("../app/components/ui/card/index").CardFooter>
export const LazyCardHeader: LazyComponent<typeof import("../app/components/ui/card/index").CardHeader>
export const LazyCardTitle: LazyComponent<typeof import("../app/components/ui/card/index").CardTitle>
export const LazyDialog: LazyComponent<typeof import("../app/components/ui/dialog/index").Dialog>
export const LazyDialogClose: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogClose>
export const LazyDialogContent: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogContent>
export const LazyDialogDescription: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogDescription>
export const LazyDialogFooter: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogFooter>
export const LazyDialogHeader: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogHeader>
export const LazyDialogOverlay: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogOverlay>
export const LazyDialogScrollContent: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogScrollContent>
export const LazyDialogTitle: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogTitle>
export const LazyDialogTrigger: LazyComponent<typeof import("../app/components/ui/dialog/index").DialogTrigger>
export const LazyDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenu>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuCheckboxItem>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuContent>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuGroup>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuItem>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuLabel>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuRadioGroup>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuRadioItem>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSeparator>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuShortcut>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSub>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSubContent>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSubTrigger>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuTrigger>
export const LazyDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuPortal>
export const LazyEmpty: LazyComponent<typeof import("../app/components/ui/empty/index").Empty>
export const LazyEmptyContent: LazyComponent<typeof import("../app/components/ui/empty/index").EmptyContent>
export const LazyEmptyDescription: LazyComponent<typeof import("../app/components/ui/empty/index").EmptyDescription>
export const LazyEmptyHeader: LazyComponent<typeof import("../app/components/ui/empty/index").EmptyHeader>
export const LazyEmptyMedia: LazyComponent<typeof import("../app/components/ui/empty/index").EmptyMedia>
export const LazyEmptyTitle: LazyComponent<typeof import("../app/components/ui/empty/index").EmptyTitle>
export const LazyInput: LazyComponent<typeof import("../app/components/ui/input/index").Input>
export const LazyNavigationMenu: LazyComponent<typeof import("../app/components/ui/navigation-menu/index").NavigationMenu>
export const LazyNavigationMenuContent: LazyComponent<typeof import("../app/components/ui/navigation-menu/index").NavigationMenuContent>
export const LazyNavigationMenuIndicator: LazyComponent<typeof import("../app/components/ui/navigation-menu/index").NavigationMenuIndicator>
export const LazyNavigationMenuItem: LazyComponent<typeof import("../app/components/ui/navigation-menu/index").NavigationMenuItem>
export const LazyNavigationMenuLink: LazyComponent<typeof import("../app/components/ui/navigation-menu/index").NavigationMenuLink>
export const LazyNavigationMenuList: LazyComponent<typeof import("../app/components/ui/navigation-menu/index").NavigationMenuList>
export const LazyNavigationMenuTrigger: LazyComponent<typeof import("../app/components/ui/navigation-menu/index").NavigationMenuTrigger>
export const LazyNavigationMenuViewport: LazyComponent<typeof import("../app/components/ui/navigation-menu/index").NavigationMenuViewport>
export const LazyPagination: LazyComponent<typeof import("../app/components/ui/pagination/index").Pagination>
export const LazyPaginationContent: LazyComponent<typeof import("../app/components/ui/pagination/index").PaginationContent>
export const LazyPaginationEllipsis: LazyComponent<typeof import("../app/components/ui/pagination/index").PaginationEllipsis>
export const LazyPaginationFirst: LazyComponent<typeof import("../app/components/ui/pagination/index").PaginationFirst>
export const LazyPaginationItem: LazyComponent<typeof import("../app/components/ui/pagination/index").PaginationItem>
export const LazyPaginationLast: LazyComponent<typeof import("../app/components/ui/pagination/index").PaginationLast>
export const LazyPaginationNext: LazyComponent<typeof import("../app/components/ui/pagination/index").PaginationNext>
export const LazyPaginationPrevious: LazyComponent<typeof import("../app/components/ui/pagination/index").PaginationPrevious>
export const LazyProgress: LazyComponent<typeof import("../app/components/ui/progress/index").Progress>
export const LazySelect: LazyComponent<typeof import("../app/components/ui/select/index").Select>
export const LazySelectContent: LazyComponent<typeof import("../app/components/ui/select/index").SelectContent>
export const LazySelectGroup: LazyComponent<typeof import("../app/components/ui/select/index").SelectGroup>
export const LazySelectItem: LazyComponent<typeof import("../app/components/ui/select/index").SelectItem>
export const LazySelectItemText: LazyComponent<typeof import("../app/components/ui/select/index").SelectItemText>
export const LazySelectLabel: LazyComponent<typeof import("../app/components/ui/select/index").SelectLabel>
export const LazySelectScrollDownButton: LazyComponent<typeof import("../app/components/ui/select/index").SelectScrollDownButton>
export const LazySelectScrollUpButton: LazyComponent<typeof import("../app/components/ui/select/index").SelectScrollUpButton>
export const LazySelectSeparator: LazyComponent<typeof import("../app/components/ui/select/index").SelectSeparator>
export const LazySelectTrigger: LazyComponent<typeof import("../app/components/ui/select/index").SelectTrigger>
export const LazySelectValue: LazyComponent<typeof import("../app/components/ui/select/index").SelectValue>
export const LazyScrollArea: LazyComponent<typeof import("../app/components/ui/scroll-area/index").ScrollArea>
export const LazyScrollBar: LazyComponent<typeof import("../app/components/ui/scroll-area/index").ScrollBar>
export const LazySeparator: LazyComponent<typeof import("../app/components/ui/separator/index").Separator>
export const LazySkeleton: LazyComponent<typeof import("../app/components/ui/skeleton/index").Skeleton>
export const LazySwitch: LazyComponent<typeof import("../app/components/ui/switch/index").Switch>
export const LazySheet: LazyComponent<typeof import("../app/components/ui/sheet/index").Sheet>
export const LazySheetClose: LazyComponent<typeof import("../app/components/ui/sheet/index").SheetClose>
export const LazySheetContent: LazyComponent<typeof import("../app/components/ui/sheet/index").SheetContent>
export const LazySheetDescription: LazyComponent<typeof import("../app/components/ui/sheet/index").SheetDescription>
export const LazySheetFooter: LazyComponent<typeof import("../app/components/ui/sheet/index").SheetFooter>
export const LazySheetHeader: LazyComponent<typeof import("../app/components/ui/sheet/index").SheetHeader>
export const LazySheetTitle: LazyComponent<typeof import("../app/components/ui/sheet/index").SheetTitle>
export const LazySheetTrigger: LazyComponent<typeof import("../app/components/ui/sheet/index").SheetTrigger>
export const LazyTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/index").Tooltip>
export const LazyTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/index").TooltipContent>
export const LazyTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/index").TooltipProvider>
export const LazyTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/index").TooltipTrigger>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue").default>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
